// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    CarbonClose: typeof import('~icons/carbon/close')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonLogoLinkedin: typeof import('~icons/carbon/logo-linkedin')['default']
    CarbonMenu: typeof import('~icons/carbon/menu')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GridiconsExternal: typeof import('~icons/gridicons/external')['default']
    Header: typeof import('./components/Header.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    SectionContact: typeof import('./components/SectionContact.vue')['default']
    SectionLanding: typeof import('./components/SectionLanding.vue')['default']
    SectionProjects: typeof import('./components/SectionProjects.vue')['default']
    SectionSkills: typeof import('./components/SectionSkills.vue')['default']
  }
}

export { }
